modLoader="javafml"
license="MIT"
loaderVersion="[43,)"
issueTrackerURL="https://github.com/zehmaria/fluidactions/issues"
displayURL="https://github.com/zehmaria/fluidactions"
logoFile="logo.png"

[[mods]]
    modId="fluidactions"
    version="${file.jarVersion}"
    displayName="Fluid Interactions"
	authors="zeh_maria"
    description="That's hot."

[[dependencies.fluidactions]]
    modId="forge"
    mandatory=true
    versionRange="[43.2.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.fluidactions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
