modLoader="javafml"
license="MIT"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/zehmaria/fluidactions/issues"
displayURL="https://github.com/zehmaria/fluidactions"
logoFile="logo.png"

[[mods]]
    modId="fluidactions"
    version="${file.jarVersion}"
    displayName="Fluid Interactions"
	authors="zeh_maria"
    description="That's hot."

[[dependencies.fluidactions]]
    modId="forge"
    mandatory=true
    versionRange="[47.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.fluidactions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
